<#
  Gate: resident_bootloader.X still says what src/boot/boot_image.psd1 says.

  The checked-in project is generated by generate_resident_project.ps1. This gate
  regenerates it into a temporary directory and compares -- so a manifest edit that
  was never regenerated, or an MPLAB X round-trip that changed what the image is
  built from, fails here instead of on a board.

  WHY NOT A BYTE-EXACT COMPARE

  Because the project's purpose is to be OPENED IN THE IDE. MPLAB X adds its own
  <Tool>/<pkob4hybrid> debugger property blocks and fills in defaults for every
  property the generator leaves out -- around 200 lines per configuration of
  peripheral-freeze settings. A byte-exact gate would fail on the very first normal
  use, and a gate that fails when nothing is wrong gets regenerated-away or
  commented out within a week; then it is not protecting anything.

  So this compares the PROJECTION the generator is the authority for, and is
  deliberately silent about the rest:

    1. the configuration name and target device
    2. the source list, against the manifest as well as against a regeneration
    3. the include directories, in order, in both the compiler and assembler blocks
    4. the preprocessor macros
    5. every property the generator emits (extra properties are MPLAB X defaults
       and are ignored; a DIFFERENT VALUE for one the generator sets is a failure)
    6. the post-build verification step
    7. that nothing anywhere names src/app/ or src/ -- the bulkhead, checked separately
       from the comparison so it fails loudly even if the manifest itself is wrong

  Exits non-zero on any difference. Companion to check_configurations.ps1, which
  does the same job for the application project -- with the difference that the
  application project is hand-maintained and its expectations are a table, while
  this one is generated and its expectation is the generator.
#>
param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot),
    # Test hook: check a mutated copy instead of the checked-in project, so the
    # self-test can prove each comparison actually fires.
    [string]$ProjectXmlDir
)

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path -LiteralPath $Root).Path
. (Join-Path $PSScriptRoot 'boot_image.ps1')
$manifest = Get-BootImageManifest -RepoRoot $repoRoot
$projectName = $manifest.ProjectName
# ONE CONFIGURATION PER DEVICE. Everything below that used to be written in the
# singular is now per device, in the manifest's own order -- see Get-BootImageDevices,
# whose determinism is what lets this gate compare rather than interpret.
$devices = @(Get-BootImageDevices -Image $manifest)
$views = [ordered]@{}
foreach ($device in $devices) {
    $views[$device] = Get-BootImageForDevice -Image $manifest -Device $device
}
$actualDir = if ([string]::IsNullOrWhiteSpace($ProjectXmlDir)) {
    Join-Path $repoRoot "$projectName.X\nbproject"
} else {
    (Resolve-Path -LiteralPath $ProjectXmlDir).Path
}
$actualConfXml = Join-Path $actualDir 'configurations.xml'

$problems = [System.Collections.Generic.List[string]]::new()
function Add-Problem { param([string]$Message) $problems.Add($Message) }

if (-not (Test-Path -LiteralPath $actualConfXml -PathType Leaf)) {
    Write-Host "Resident project gate FAILED" -ForegroundColor Red
    Write-Host "  $actualConfXml does not exist."
    Write-Host '  Generate it: pwsh buildtools/generate_resident_project.ps1'
    exit 1
}

# The project's Makefile must exist and be the stub the generator writes. The IDE does
# NOT create it, and its absence is reported as "make: Makefile: No such file or
# directory" AFTER a successful clean -- which reads like a broken toolchain and cost
# three IDE build attempts and a trip through Project Properties before the real cause
# was found. Checked by content, not just existence, because a truncated or
# hand-"fixed" stub fails the same way and just as unhelpfully.
$actualMakefile = Join-Path (Split-Path -Parent $actualDir) 'Makefile'
if (-not (Test-Path -LiteralPath $actualMakefile -PathType Leaf)) {
    Add-Problem ("$projectName.X/Makefile is missing. MPLAB X does not create it -- an IDE " +
                 "build fails with `"make: Makefile: No such file or directory`". " +
                 'Regenerate: pwsh buildtools/generate_resident_project.ps1')
    $actualMakefile = $null
}


# --- regenerate into a temporary directory ---------------------------------
# Under the OS temp dir, not in the repo: a gate that writes into the working tree
# would show up as a dirty file and teach people to ignore dirty files.
$tempDir = Join-Path ([IO.Path]::GetTempPath()) ("resident_proj_gate_" + [Guid]::NewGuid().ToString('N'))
try {
    # Not checked via $LASTEXITCODE: a .ps1 that returns without calling exit leaves it
    # at whatever the last NATIVE command set, so testing it here read a stale value and
    # reported a failure that had not happened. The generator runs with
    # $ErrorActionPreference = 'Stop' and throws, which propagates; the file's existence
    # is the remaining thing worth asserting.
    & (Join-Path $PSScriptRoot 'generate_resident_project.ps1') -Root $repoRoot -OutDir $tempDir -Quiet
    $expectedConfXml = Join-Path $tempDir "$projectName.X\nbproject\configurations.xml"
    if (-not (Test-Path -LiteralPath $expectedConfXml -PathType Leaf)) {
        throw "generate_resident_project.ps1 produced no configurations.xml in $tempDir."
    }

    if ($null -ne $actualMakefile) {
        $expectedMakefile = Join-Path $tempDir "$projectName.X\Makefile"
        $normalise = { param($p) (Get-Content -LiteralPath $p -Raw) -replace "`r`n", "`n" }
        if ((& $normalise $actualMakefile) -ne (& $normalise $expectedMakefile)) {
            Add-Problem ("$projectName.X/Makefile differs from the one the generator writes. " +
                         'It is a fixed stub -- do not hand-edit it.')
        }
    }

    [xml]$actual = Get-Content -LiteralPath $actualConfXml -Raw
    [xml]$expected = Get-Content -LiteralPath $expectedConfXml -Raw

    # EXACTLY AS MANY CONFIGURATIONS AS THE MANIFEST HAS DEVICES, each looked up BY NAME
    # and each checked. This was "exactly one configuration; a second configuration is a
    # second image nobody checks" while there was one part -- and the invariant it was
    # protecting is unchanged: no configuration may exist that this gate does not check.
    # Counting them is what enforces that, since a configuration the manifest does not
    # name cannot be found by name and would otherwise simply be skipped.
    function Get-ConfByName {
        param([xml]$Doc, [string]$Name, [string]$Which)
        $found = @(@($Doc.configurationDescriptor.confs.conf) | Where-Object { $_.name -eq $Name })
        if ($found.Count -ne 1) {
            Add-Problem ("the $Which project has $($found.Count) configuration(s) named '$Name'; " +
                         'the manifest names it exactly once. build/ and dist/ are named after it.')
            return $null
        }
        return $found[0]
    }
    foreach ($side in @(@{ Doc = $actual; Which = 'checked-in' },
                        @{ Doc = $expected; Which = 'regenerated' })) {
        $count = @($side.Doc.configurationDescriptor.confs.conf).Count
        if ($count -ne $devices.Count) {
            Add-Problem ("the $($side.Which) project has $count configuration(s); " +
                         "src/boot/boot_image.psd1 has $($devices.Count) device(s). A configuration " +
                         'the manifest does not name is an image nobody checks.')
        }
    }

    foreach ($device in $devices) {
        $view = $views[$device]
        $confName = $view.ConfigurationName
        $actualConf = Get-ConfByName -Doc $actual -Name $confName -Which 'checked-in'
        $expectedConf = Get-ConfByName -Doc $expected -Name $confName -Which 'regenerated'
        if ($null -eq $actualConf -or $null -eq $expectedConf) { continue }

        # 1. The target device. The name matched by construction (it is how the
        # configuration was found), so what remains is that the configuration named after
        # this device is actually built for it -- the field that was hard-coded to the
        # MPS512 until the manifest grew a second part.
        $actualDevice = $actualConf.toolsSet.targetDevice
        $expectedDevice = $expectedConf.toolsSet.targetDevice
        if ($actualDevice -ne $expectedDevice) {
            Add-Problem "$confName target device is '$actualDevice'; expected '$expectedDevice'."
        }

        # 2. Every other device's linker script is EXCLUDED from this configuration.
        # MPLAB X passes every registered script to the linker, so an unexcluded one is
        # not an unused file -- it is a second --script= and the image would be linked to
        # whichever the linker took last. This is the invariant that makes one project
        # for several devices safe at all, so it is asserted rather than inherited from
        # the comparison.
        foreach ($other in $devices) {
            if ($other -eq $device) { continue }
            $otherPath = '../' + $views[$other].LinkerScript.Replace('\', '/')
            $item = @($actualConf.SelectNodes("./item[@path='$otherPath']"))
            if ($item.Count -eq 0) {
                Add-Problem ("$confName does not exclude $otherPath. MPLAB X hands every registered " +
                             'linker script to the linker, so this one would be a second --script=.')
            } elseif ($item[0].GetAttribute('ex') -ne 'true') {
                Add-Problem ("$confName has $otherPath with ex='$($item[0].GetAttribute('ex'))'; " +
                             "it must be ex='true' -- it is another device's linker script.")
            }
        }
        # ...and this device's own script is NOT excluded, which is the same mistake the
        # other way around: the link would fall back to the DFP's default script and
        # place the image wherever that says, without failing.
        $ownPath = '../' + $view.LinkerScript.Replace('\', '/')
        $ownItem = @($actualConf.SelectNodes("./item[@path='$ownPath']"))
        if ($ownItem.Count -ne 0 -and $ownItem[0].GetAttribute('ex') -eq 'true') {
            Add-Problem ("$confName excludes its OWN linker script $ownPath. The link would then use " +
                         "the device pack's default script and place the image outside the boot region.")
        }

        # 3-5. Properties. Only the keys the generator emits are compared; anything
        # else in the file is an MPLAB X default and none of this gate's business.
        foreach ($block in @('C30', 'C30-AS', 'C30-LD', 'C30Global')) {
            $expectedProps = @($expectedConf.SelectNodes("./$block/property"))
            foreach ($p in $expectedProps) {
                $key = $p.GetAttribute('key')
                $want = $p.GetAttribute('value')
                $got = @($actualConf.SelectNodes("./$block/property[@key='$key']") |
                    ForEach-Object { $_.GetAttribute('value') })
                if ($got.Count -eq 0) {
                    Add-Problem "$confName <$block> property '$key' is absent from the project; the manifest sets it to '$want'."
                } elseif ($got[0] -ne $want) {
                    Add-Problem ("$confName <$block> property '$key' is '$($got[0])'; the manifest says '$want'. " +
                                 'Edit src/boot/boot_image.psd1 and regenerate -- do not edit the project.')
                }
            }
        }

        # 6. The post-build verification step.
        $actualPost = $actualConf.makeCustomizationType.makeCustomizationPostStep
        $expectedPost = $expectedConf.makeCustomizationType.makeCustomizationPostStep
        $actualPostEnabled = $actualConf.makeCustomizationType.makeCustomizationPostStepEnabled
        if ($actualPostEnabled -ne 'true') {
            Add-Problem ("$confName has the post-build step disabled. An IDE build would then produce a " +
                         'resident image with none of verify_resident_image.ps1 run on it -- and an IDE ' +
                         'build is exactly the one most likely to be a one-off nobody checks.')
        }
        if ($actualPost -ne $expectedPost) {
            Add-Problem "$confName post-build step is '$actualPost'; expected '$expectedPost'."
        }
    }

    # 2. Registered files -- against the regeneration AND against the manifest directly,
    # so a generator bug that dropped a source from both sides cannot pass. Project-wide
    # rather than per configuration: the itemPath list is the project's file tree, which
    # every configuration shares (what differs per configuration is the ex="true" above).
    $actualItems = @($actual.SelectNodes('//itemPath') | ForEach-Object { $_.InnerText } | Sort-Object)
    $expectedItems = @($expected.SelectNodes('//itemPath') | ForEach-Object { $_.InnerText } | Sort-Object)
    foreach ($missing in @($expectedItems | Where-Object { $actualItems -notcontains $_ })) {
        Add-Problem "source registered by the manifest but MISSING from the project: $missing"
    }
    foreach ($extra in @($actualItems | Where-Object { $expectedItems -notcontains $_ })) {
        Add-Problem ("source registered in the project but NOT in src/boot/boot_image.psd1: $extra " +
                     '(the IDE can add files; the manifest is the authority)')
    }
    # EVERY device's linker script, not one: the project registers all of them and each
    # configuration excludes the ones that are not its own.
    $manifestItems = @(@($manifest.Sources) +
        @($devices | ForEach-Object { $views[$_].LinkerScript }) |
        ForEach-Object { '../' + $_.Replace('\', '/') } | Sort-Object -Unique)
    foreach ($missing in @($manifestItems | Where-Object { $actualItems -notcontains $_ })) {
        Add-Problem "src/boot/boot_image.psd1 names '$missing' but the project does not register it."
    }

    # 7. The bulkhead. Checked against the CHECKED-IN file directly rather than by
    # comparison, so it still fails if the manifest itself acquired an src/app/ entry --
    # a comparison would happily agree that both sides are wrong.
    #
    # The pattern names the APPLICATION TREE, which since the src/ reorg is ..\src\app.
    # A bare "src" is NOT a synonym for it any more (..\src\boot and ..\src\shared are
    # the image's own includes), so matching "src" alone would fire on every build. The
    # optional prefix keeps a pre-reorg bare ..\app caught too.
    # <item path="..."> is scanned too: those are the per-configuration override blocks,
    # and MPLAB X writes one for any file it is given an opinion about -- so it is a
    # second way an application path could arrive in this project.
    $texts = @($actual.SelectNodes('//itemPath') | ForEach-Object { $_.InnerText }) +
             @($actual.SelectNodes('//item') | ForEach-Object { $_.GetAttribute('path') }) +
             @($actual.SelectNodes('//property') | ForEach-Object { $_.GetAttribute('value') })
    foreach ($t in $texts) {
        if ([string]::IsNullOrWhiteSpace($t)) { continue }
        foreach ($piece in ($t -split '[;,]')) {
            if ($piece -match '(?<![A-Za-z0-9_-])\.\.[\\/](?:src[\\/])?app(?=[\\/]|$)') {
                Add-Problem ("the project names the application tree: '$piece'. The resident image " +
                             'compiles nothing from src/app/ (reorg step 4). MPLAB X offers to add an ' +
                             'include directory when a header is not found -- accepting that offer is ' +
                             'how this appears. Vendor the file into src/boot/ instead.')
            }
        }
    }
}
finally {
    if (Test-Path -LiteralPath $tempDir) {
        Remove-Item -LiteralPath $tempDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}

# --- report ----------------------------------------------------------------
Write-Host "Resident project gate: $actualConfXml"
Write-Host ("  {0} configuration(s), {1} source(s), {2} include dir(s), from src/boot/boot_image.psd1" -f
            $devices.Count, @($manifest.Sources).Count, @($manifest.Includes).Count)
foreach ($device in $devices) {
    Write-Host ("    {0}  ({1})" -f $views[$device].ConfigurationName, $device)
}

if ($problems.Count -gt 0) {
    Write-Host ''
    Write-Host "Resident project gate FAILED: $($problems.Count) problem(s)" -ForegroundColor Red
    foreach ($p in $problems) { Write-Host "  - $p" }
    Write-Host ''
    Write-Host 'src/boot/boot_image.psd1 is the authority. Edit it, then run:'
    Write-Host '  pwsh buildtools/generate_resident_project.ps1'
    exit 1
}

Write-Host 'Resident project gate: PASS'
exit 0
